/**
 * Коды авиакомпаний
 */
const AIRLINES = {
  'SU': 'Аэрофлот',
  'S7': 'S7 Airlines',
  'EY': 'Etihad Airways',
  'EK': 'Emirates',
  'FZ': 'Flydubai',
  'UT': 'Utair',
  'U6': 'Уральские авиалинии',
  'WZ': 'Red Wings',
  'DP': 'Pobeda',
  'N4': 'Nordwind Airlines',
  'YC': 'Yakutia Airlines',
  'KC': 'Air Astana',
  'TK': 'Turkish Airlines',
  'QR': 'Qatar Airways',
  'LH': 'Lufthansa',
  'AF': 'Air France',
  'KL': 'KLM',
  'BA': 'British Airways',
  'AZ': 'ITA Airways',
  'OS': 'Austrian Airlines',
  'LO': 'LOT Polish Airlines',
  'SN': 'Brussels Airlines',
  'AY': 'Finnair',
  'SK': 'SAS Scandinavian',
  'IB': 'Iberia',
  'VY': 'Vueling',
  'FR': 'Ryanair',
  'W6': 'Wizz Air',
  'U2': 'easyJet',
  'PC': 'Pegasus Airlines',
  'PS': 'Ukraine International',
  'HY': 'Uzbekistan Airways',
  'B2': 'Belavia',
  'J2': 'Azerbaijan Airlines',
  'KC': 'Air Astana',
  'DV': 'Scat Airlines',
  'FV': 'Rossiya Airlines',
  '5N': 'Smartavia',
  'I4': 'IrAero',
  'ZF': 'Azimuth',
  '6W': 'Saratov Airlines',
  'D2': 'Severstal Air Company',
  'GH': 'Grodno Airlines',
  'CZ': 'China Southern',
  'MU': 'China Eastern',
  'CA': 'Air China',
  'HU': 'Hainan Airlines',
  'SC': 'Shandong Airlines',
  '3U': 'Sichuan Airlines',
  'NH': 'All Nippon Airways',
  'JL': 'Japan Airlines',
  'OZ': 'Asiana Airlines',
  'KE': 'Korean Air',
  'VN': 'Vietnam Airlines',
  'TG': 'Thai Airways',
  'SQ': 'Singapore Airlines',
  'MH': 'Malaysia Airlines',
  'GA': 'Garuda Indonesia',
  'AI': 'Air India',
  'SV': 'Saudia',
  'MS': 'Egyptair',
  'ET': 'Ethiopian Airlines',
  'KQ': 'Kenya Airways',
  'SA': 'South African Airways',
  'AC': 'Air Canada',
  'UA': 'United Airlines',
  'AA': 'American Airlines',
  'DL': 'Delta Air Lines',
  'B6': 'JetBlue Airways',
  'WN': 'Southwest Airlines',
  'AS': 'Alaska Airlines',
  'AM': 'Aeromexico',
  'CM': 'Copa Airlines',
  'AR': 'Aerolineas Argentinas',
  'LA': 'LATAM Airlines',
  'G3': 'GOL Linhas Aereas',
  'QF': 'Qantas',
  'NZ': 'Air New Zealand',
  'VA': 'Virgin Australia'
};

/**
 * Популярные аэропорты
 */
const AIRPORTS = {
  // Россия
  'MOW': 'Москва (все аэропорты)',
  'SVO': 'Москва Шереметьево',
  'DME': 'Москва Домодедово',
  'VKO': 'Москва Внуково',
  'LED': 'Санкт-Петербург Пулково',
  'SVX': 'Екатеринбург Кольцово',
  'KJA': 'Красноярск Емельяново',
  'OVB': 'Новосибирск Толмачёво',
  'KZN': 'Казань',
  'ROV': 'Ростов-на-Дону Платов',
  'AER': 'Сочи Адлер',
  'KRR': 'Краснодар Пашковский',
  'UFA': 'Уфа',
  'VVO': 'Владивосток Кневичи',
  'KHV': 'Хабаровск Новый',
  'IKT': 'Иркутск',
  'SIP': 'Симферополь',
  'UUS': 'Южно-Сахалинск Хомутово',
  'MMK': 'Мурманск',
  'ARH': 'Архангельск Талаги',
  'ASF': 'Астрахань Нариманово',
  'BTK': 'Братск',
  'CEK': 'Челябинск Баландино',
  'CNN': 'Чита Кадала',
  'GOJ': 'Нижний Новгород Стригино',
  'IWA': 'Иваново Южный',
  'KEJ': 'Кемерово Леонова',
  'KGD': 'Калининград Храброво',
  'MRV': 'Минеральные Воды',
  'NOZ': 'Новокузнецк Спиченково',
  'NUX': 'Новый Уренгой',
  'OMS': 'Омск Центральный',
  'PEE': 'Пермь Большое Савино',
  'PKC': 'Петропавловск-Камчатский Елизово',
  'REN': 'Оренбург Центральный',
  'RTW': 'Саратов Гагарин',
  'SGC': 'Сургут',
  'TOF': 'Томск Богашёво',
  'TJM': 'Тюмень Рощино',
  'VOG': 'Волгоград Гумрак',
  'VOZ': 'Воронеж Чертовицкое',
  'YKS': 'Якутск',

  // Европа
  'IST': 'Стамбул (все аэропорты)',
  'SAW': 'Стамбул Сабиха Гёкчен',
  'AYT': 'Анталья',
  'ESB': 'Анкара Эсенбога',
  'ADB': 'Измир Аднан Мендерес',
  'DLM': 'Даламан',
  'BJV': 'Бодрум Милас',
  'GZT': 'Газиантеп',
  'TZX': 'Трабзон',
  'LHR': 'Лондон Хитроу',
  'LGW': 'Лондон Гатвик',
  'STN': 'Лондон Станстед',
  'CDG': 'Париж Шарль-де-Голль',
  'ORY': 'Париж Орли',
  'FRA': 'Франкфурт',
  'MUC': 'Мюнхен',
  'BCN': 'Барселона',
  'MAD': 'Мадрид',
  'FCO': 'Рим Фьюмичино',
  'MXP': 'Милан Мальпенса',
  'VCE': 'Венеция Марко Поло',
  'NAP': 'Неаполь',
  'AMS': 'Амстердам Схипхол',
  'VIE': 'Вена Швехат',
  'ZRH': 'Цюрих',
  'GVA': 'Женева',
  'PRG': 'Прага Вацлава Гавела',
  'WAW': 'Варшава Шопен',
  'BUD': 'Будапешт Ференца Листа',
  'ATH': 'Афины Элефтериос Веницелос',
  'HER': 'Ираклион',
  'RHO': 'Родос',
  'SKG': 'Салоники',
  'LIS': 'Лиссабон Портела',
  'OPO': 'Порту Франсишку Са Карнейру',
  'DUB': 'Дублин',
  'CPH': 'Копенгаген Каструп',
  'ARN': 'Стокгольм Арланда',
  'OSL': 'Осло Гардермуэн',
  'HEL': 'Хельсинки Вантаа',
  'BRU': 'Брюссель Завентем',
  'LUX': 'Люксембург',

  // Ближний Восток и Азия
  'DXB': 'Дубай',
  'AUH': 'Абу-Даби',
  'SHJ': 'Шарджа',
  'DOH': 'Доха Хамад',
  'BAH': 'Бахрейн',
  'KWI': 'Кувейт',
  'MCT': 'Маскат',
  'RUH': 'Эр-Рияд',
  'JED': 'Джидда',
  'CAI': 'Каир',
  'SSH': 'Шарм-эль-Шейх',
  'HRG': 'Хургада',
  'TLV': 'Тель-Авив Бен-Гурион',
  'AMM': 'Амман',
  'BEY': 'Бейрут',
  'TBS': 'Тбилиси',
  'EVN': 'Ереван Звартноц',
  'GYD': 'Баку Гейдар Алиев',
  'TAS': 'Ташкент',
  'ALA': 'Алматы',
  'NQZ': 'Астана (Нур-Султан)',
  'FRU': 'Бишкек Манас',
  'DYU': 'Душанбе',
  'ASB': 'Ашхабад',
  'BKK': 'Бангкок Суварнабхуми',
  'HKT': 'Пхукет',
  'CNX': 'Чианг Май',
  'SGN': 'Хошимин Тан Сон Нхат',
  'HAN': 'Ханой Ной Бай',
  'DAD': 'Дананг',
  'SIN': 'Сингапур Чанги',
  'KUL': 'Куала-Лумпур',
  'CGK': 'Джакарта Сукарно-Хатта',
  'DPS': 'Бали Нгурах-Рай',
  'MNL': 'Манила Ниной Акино',
  'HKG': 'Гонконг',
  'PEK': 'Пекин Столичный',
  'PVG': 'Шанхай Пудун',
  'CAN': 'Гуанчжоу Байюнь',
  'NRT': 'Токио Нарита',
  'HND': 'Токио Ханеда',
  'KIX': 'Осака Кансай',
  'ICN': 'Сеул Инчхон',
  'DEL': 'Дели Индира Ганди',
  'BOM': 'Мумбаи Чатрапати Шиваджи',
  'GOI': 'Гоа Даболим',
  'CMB': 'Коломбо Бандаранайке',
  'MLE': 'Мале Велана',

  // Америка
  'JFK': 'Нью-Йорк Кеннеди',
  'EWR': 'Нью-Йорк Ньюарк',
  'LGA': 'Нью-Йорк Ла-Гуардия',
  'LAX': 'Лос-Анджелес',
  'SFO': 'Сан-Франциско',
  'ORD': 'Чикаго О\'Хара',
  'MIA': 'Майами',
  'LAS': 'Лас-Вегас',
  'SEA': 'Сиэтл-Такома',
  'BOS': 'Бостон Логан',
  'YYZ': 'Торонто Пирсон',
  'YVR': 'Ванкувер',
  'YUL': 'Монреаль Трюдо',
  'MEX': 'Мехико',
  'CUN': 'Канкун',
  'GRU': 'Сан-Паулу Гуарульюс',
  'GIG': 'Рио-де-Жанейро Галеан',
  'EZE': 'Буэнос-Айрес Эсейса',
  'SCL': 'Сантьяго',
  'BOG': 'Богота Эльдорадо',
  'LIM': 'Лима Хорхе Чавес',

  // Африка и Океания
  'ADD': 'Аддис-Абеба Боле',
  'NBO': 'Найроби Джомо Кениата',
  'CPT': 'Кейптаун',
  'JNB': 'Йоханнесбург Тамбо',
  'SYD': 'Сидней Кингсфорд Смит',
  'MEL': 'Мельбурн Талламарин',
  'AKL': 'Окленд'
};

/**
 * Валюты
 */
const CURRENCIES = {
  'RUB': { symbol: '₽', name: 'Российский рубль' },
  'USD': { symbol: '$', name: 'Доллар США' },
  'EUR': { symbol: '€', name: 'Евро' },
  'GBP': { symbol: '£', name: 'Фунт стерлингов' },
  'CNY': { symbol: '¥', name: 'Китайский юань' },
  'JPY': { symbol: '¥', name: 'Японская иена' },
  'KRW': { symbol: '₩', name: 'Южнокорейская вона' },
  'THB': { symbol: '฿', name: 'Тайский бат' },
  'AED': { symbol: 'د.إ', name: 'Дирхам ОАЭ' },
  'TRY': { symbol: '₺', name: 'Турецкая лира' }
};

/**
 * Лимиты для пользователей
 */
const LIMITS = {
  FREE: {
    FLEXIBLE_ROUTES: 1,
    FIXED_ROUTES: 3,
    MAX_COMBINATIONS: 20
  },
  PREMIUM: {
    FLEXIBLE_ROUTES: 10,
    FIXED_ROUTES: 20,
    MAX_COMBINATIONS: 100
  },
  ADMIN: {
    FLEXIBLE_ROUTES: 999,
    FIXED_ROUTES: 999,
    MAX_COMBINATIONS: 999
  }
};

/**
 * ID администратора
 */
const ADMIN_ID = 341508411;

module.exports = {
  AIRLINES,
  AIRPORTS,
  CURRENCIES,
  LIMITS,
  ADMIN_ID
};
