/**
 * Коды авиакомпаний
 */
const AIRLINES = {
  'SU': 'Аэрофлот',
  'S7': 'S7 Airlines',
  'EY': 'Etihad Airways',
  'EK': 'Emirates',
  'FZ': 'Flydubai',
  'UT': 'Utair',
  'U6': 'Уральские авиалинии',
  'WZ': 'Red Wings',
  'DP': 'Pobeda',
  'N4': 'Nordwind Airlines',
  'YC': 'Yakutia Airlines',
  'KC': 'Air Astana',
  'TK': 'Turkish Airlines',
  'QR': 'Qatar Airways',
  'LH': 'Lufthansa',
  'AF': 'Air France',
  'KL': 'KLM',
  'BA': 'British Airways',
  'AZ': 'ITA Airways',
  'OS': 'Austrian Airlines',
  'LO': 'LOT Polish Airlines',
  'SN': 'Brussels Airlines',
  'AY': 'Finnair',
  'SK': 'SAS Scandinavian',
  'IB': 'Iberia',
  'VY': 'Vueling',
  'FR': 'Ryanair',
  'W6': 'Wizz Air',
  'U2': 'easyJet',
  'PC': 'Pegasus Airlines',
  'PS': 'Ukraine International',
  'HY': 'Uzbekistan Airways',
  'B2': 'Belavia',
  'J2': 'Azerbaijan Airlines',
  'KC': 'Air Astana',
  'DV': 'Scat Airlines',
  'FV': 'Rossiya Airlines',
  '5N': 'Smartavia',
  'I4': 'IrAero',
  'ZF': 'Azimuth',
  '6W': 'Saratov Airlines',
  'D2': 'Severstal Air Company',
  'GH': 'Grodno Airlines',
  'CZ': 'China Southern',
  'MU': 'China Eastern',
  'CA': 'Air China',
  'HU': 'Hainan Airlines',
  'SC': 'Shandong Airlines',
  '3U': 'Sichuan Airlines',
  'NH': 'All Nippon Airways',
  'JL': 'Japan Airlines',
  'OZ': 'Asiana Airlines',
  'KE': 'Korean Air',
  'VN': 'Vietnam Airlines',
  'TG': 'Thai Airways',
  'SQ': 'Singapore Airlines',
  'MH': 'Malaysia Airlines',
  'GA': 'Garuda Indonesia',
  'AI': 'Air India',
  'SV': 'Saudia',
  'MS': 'Egyptair',
  'ET': 'Ethiopian Airlines',
  'KQ': 'Kenya Airways',
  'SA': 'South African Airways',
  'AC': 'Air Canada',
  'UA': 'United Airlines',
  'AA': 'American Airlines',
  'DL': 'Delta Air Lines',
  'B6': 'JetBlue Airways',
  'WN': 'Southwest Airlines',
  'AS': 'Alaska Airlines',
  'AM': 'Aeromexico',
  'CM': 'Copa Airlines',
  'AR': 'Aerolineas Argentinas',
  'LA': 'LATAM Airlines',
  'G3': 'GOL Linhas Aereas',
  'QF': 'Qantas',
  'NZ': 'Air New Zealand',
  'VA': 'Virgin Australia'
};

/**
 * ID администратора
 */

module.exports = {
  AIRLINES,
};
